name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Bağimliliklari yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest torch torchvision

      - name: Lint code
        run: echo "Linting repository" 

      - name: Testleri detayli çaliştir
        run: |
          pytest --disable-warnings -v test/test.py

      - name: Testlerin sonucu
        run: |
          echo "Unit testler çaliştirildi ve sonuçlar görüntülendi"
